<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="10" ignored="0" total="11" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="HealthCheckSuite" duration-ms="55153" started-at="2020-06-02T11:02:45Z" finished-at="2020-06-02T11:03:40Z">
    <groups>
      <group name="actuatorTest">
        <method signature="ActuatorTest.actuatorHealthTest(java.lang.Object, java.lang.Object)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="actuatorHealthTest" class="io.mosip.actuator.healthcheck.test.ActuatorTest"/>
      </group> <!-- actuatorTest -->
      <group name="preReg">
        <method signature="PreRegistrationSmoke.bookAppointment()[pri:5, instance:io.mosip.preregistration.tests.PreRegistrationSmoke@77f03bb1]" name="bookAppointment" class="io.mosip.preregistration.tests.PreRegistrationSmoke"/>
        <method signature="PreRegistrationSmoke.createApplication()[pri:2, instance:io.mosip.preregistration.tests.PreRegistrationSmoke@77f03bb1]" name="createApplication" class="io.mosip.preregistration.tests.PreRegistrationSmoke"/>
        <method signature="PreRegistrationSmoke.documentUpload()[pri:3, instance:io.mosip.preregistration.tests.PreRegistrationSmoke@77f03bb1]" name="documentUpload" class="io.mosip.preregistration.tests.PreRegistrationSmoke"/>
        <method signature="PreRegistrationSmoke.fetchCenter()[pri:4, instance:io.mosip.preregistration.tests.PreRegistrationSmoke@77f03bb1]" name="fetchCenter" class="io.mosip.preregistration.tests.PreRegistrationSmoke"/>
        <method signature="PreRegistrationSmoke.generateOtp()[pri:1, instance:io.mosip.preregistration.tests.PreRegistrationSmoke@77f03bb1]" name="generateOtp" class="io.mosip.preregistration.tests.PreRegistrationSmoke"/>
      </group> <!-- preReg -->
    </groups>
    <test name="HealthCheckTest" duration-ms="55153" started-at="2020-06-02T11:02:45Z" finished-at="2020-06-02T11:03:40Z">
      <class name="io.mosip.actuator.healthcheck.test.ActuatorTest">
        <test-method status="PASS" signature="getTestCaseName(java.lang.reflect.Method, [Ljava.lang.Object;, org.testng.ITestContext)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="getTestCaseName" is-config="true" duration-ms="3" started-at="2020-06-02T16:33:34Z" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void io.mosip.actuator.healthcheck.test.ActuatorTest.actuatorHealthTest(java.lang.Object,java.lang.Object)]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.Object;@3e55eeb9]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@44a13699]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestCaseName -->
        <test-method status="FAIL" signature="actuatorHealthTest(java.lang.Object, java.lang.Object)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="id-repository" duration-ms="2" started-at="2020-06-02T16:33:34Z" data-provider="serviceMap" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[id-repository]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{id-repository-identity-service=UP, id-repository-vid-service=Down}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at io.mosip.actuator.healthcheck.test.ActuatorTest.actuatorHealthTest(ActuatorTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:72)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.main(MosipTestRunner.java:35)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- id-repository -->
        <test-method status="PASS" signature="getTestCaseName(java.lang.reflect.Method, [Ljava.lang.Object;, org.testng.ITestContext)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="getTestCaseName" is-config="true" duration-ms="0" started-at="2020-06-02T16:33:34Z" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void io.mosip.actuator.healthcheck.test.ActuatorTest.actuatorHealthTest(java.lang.Object,java.lang.Object)]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.Object;@3cc2e3e]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@44a13699]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestCaseName -->
        <test-method status="PASS" signature="setResultTestName(org.testng.ITestResult)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="setResultTestName" is-config="true" duration-ms="0" started-at="2020-06-02T16:33:34Z" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=actuatorHealthTest status=FAILURE method=ActuatorTest.actuatorHealthTest(java.lang.Object, java.lang.Object)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setResultTestName -->
        <test-method status="FAIL" signature="actuatorHealthTest(java.lang.Object, java.lang.Object)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="pre-registration" duration-ms="0" started-at="2020-06-02T16:33:34Z" data-provider="serviceMap" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[pre-registration]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{pre-registration-document-service=Down, pre-registration-notification-service=UP, pre-registration-translitration-service=UP, pre-registration-batchjob-service=Down, pre-registration-login-service=UP, pre-registration-generateqrcode-service=UP, pre-registration-booking-service=Down, pre-registration-demographic-service=Down, pre-registration-ui=Down, pre-registration-datasync-service=Down}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at io.mosip.actuator.healthcheck.test.ActuatorTest.actuatorHealthTest(ActuatorTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:72)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.main(MosipTestRunner.java:35)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pre-registration -->
        <test-method status="PASS" signature="setResultTestName(org.testng.ITestResult)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="setResultTestName" is-config="true" duration-ms="0" started-at="2020-06-02T16:33:34Z" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=actuatorHealthTest status=FAILURE method=ActuatorTest.actuatorHealthTest(java.lang.Object, java.lang.Object)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setResultTestName -->
        <test-method status="PASS" signature="setResultTestName(org.testng.ITestResult)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="setResultTestName" is-config="true" duration-ms="1" started-at="2020-06-02T16:33:34Z" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=actuatorHealthTest status=FAILURE method=ActuatorTest.actuatorHealthTest(java.lang.Object, java.lang.Object)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setResultTestName -->
        <test-method status="FAIL" signature="actuatorHealthTest(java.lang.Object, java.lang.Object)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="registration-processor" duration-ms="0" started-at="2020-06-02T16:33:34Z" data-provider="serviceMap" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[registration-processor]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{registration-processor-packet-uploader-stage=Down, registration-processor-request-handler-service=Down, registration-processor-bio-dedupe-service=Down, registration-processor-external-integration-service=Down, registration-processor-print-service=Down, registration-processor-manual-verification-stage=Down, registration-processor-abis=Down}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at io.mosip.actuator.healthcheck.test.ActuatorTest.actuatorHealthTest(ActuatorTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:72)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.main(MosipTestRunner.java:35)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registration-processor -->
        <test-method status="PASS" signature="getTestCaseName(java.lang.reflect.Method, [Ljava.lang.Object;, org.testng.ITestContext)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="getTestCaseName" is-config="true" duration-ms="0" started-at="2020-06-02T16:33:34Z" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void io.mosip.actuator.healthcheck.test.ActuatorTest.actuatorHealthTest(java.lang.Object,java.lang.Object)]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.Object;@4e14d520]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@44a13699]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestCaseName -->
        <test-method status="PASS" signature="getTestCaseName(java.lang.reflect.Method, [Ljava.lang.Object;, org.testng.ITestContext)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="getTestCaseName" is-config="true" duration-ms="5" started-at="2020-06-02T16:33:34Z" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void io.mosip.actuator.healthcheck.test.ActuatorTest.actuatorHealthTest(java.lang.Object,java.lang.Object)]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.Object;@4189e668]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@44a13699]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestCaseName -->
        <test-method status="PASS" signature="setResultTestName(org.testng.ITestResult)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="setResultTestName" is-config="true" duration-ms="0" started-at="2020-06-02T16:33:34Z" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=actuatorHealthTest status=FAILURE method=ActuatorTest.actuatorHealthTest(java.lang.Object, java.lang.Object)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setResultTestName -->
        <test-method status="PASS" signature="getTestCaseName(java.lang.reflect.Method, [Ljava.lang.Object;, org.testng.ITestContext)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="getTestCaseName" is-config="true" duration-ms="0" started-at="2020-06-02T16:33:34Z" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void io.mosip.actuator.healthcheck.test.ActuatorTest.actuatorHealthTest(java.lang.Object,java.lang.Object)]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.Object;@3a589eed]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@44a13699]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestCaseName -->
        <test-method status="FAIL" signature="actuatorHealthTest(java.lang.Object, java.lang.Object)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="kernel" duration-ms="0" started-at="2020-06-02T16:33:34Z" data-provider="serviceMap" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[kernel]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{kernel-otpmanager-service=UP, kernel-tokenidgenerator-service=Down, kernel-licensekeymanager-service=Down, kernel-auth-service=UP, kernel-ridgenerator-service=UP, kernel-uingenerator-service=Down, kernel-emailnotification-service=Down, kernel-masterdata-service=UP, kernel-auditmanager-service=UP, kernel-syncdata-service=UP, kernel-applicanttype-service=Down, kernel-config-server=UP, kernel-smsnotification-service=Down, kernel-keymanager-service=UP, kernel-signature-service=Down, kernel-cryptomanager-service=Down}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at io.mosip.actuator.healthcheck.test.ActuatorTest.actuatorHealthTest(ActuatorTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:72)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.main(MosipTestRunner.java:35)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- kernel -->
        <test-method status="FAIL" signature="actuatorHealthTest(java.lang.Object, java.lang.Object)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="admin" duration-ms="1" started-at="2020-06-02T16:33:34Z" data-provider="serviceMap" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{admin-ui=Down, admin-service=UP}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at io.mosip.actuator.healthcheck.test.ActuatorTest.actuatorHealthTest(ActuatorTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:72)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.main(MosipTestRunner.java:35)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- admin -->
        <test-method status="PASS" signature="setResultTestName(org.testng.ITestResult)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="setResultTestName" is-config="true" duration-ms="0" started-at="2020-06-02T16:33:34Z" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=actuatorHealthTest status=FAILURE method=ActuatorTest.actuatorHealthTest(java.lang.Object, java.lang.Object)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setResultTestName -->
        <test-method status="PASS" signature="getTestCaseName(java.lang.reflect.Method, [Ljava.lang.Object;, org.testng.ITestContext)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="getTestCaseName" is-config="true" duration-ms="1" started-at="2020-06-02T16:33:34Z" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void io.mosip.actuator.healthcheck.test.ActuatorTest.actuatorHealthTest(java.lang.Object,java.lang.Object)]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.Object;@5807ea46]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@44a13699]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestCaseName -->
        <test-method status="PASS" signature="actuatorHealthTest(java.lang.Object, java.lang.Object)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="authentication" duration-ms="0" started-at="2020-06-02T16:33:34Z" data-provider="serviceMap" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[authentication]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{authentication-service=UP, authentication-internal-service=UP, authentication-otp-service=UP, authentication-kyc-service=UP}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- authentication -->
        <test-method status="PASS" signature="setResultTestName(org.testng.ITestResult)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946]" name="setResultTestName" is-config="true" duration-ms="0" started-at="2020-06-02T16:33:34Z" finished-at="2020-06-02T16:33:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=actuatorHealthTest status=SUCCESS method=ActuatorTest.actuatorHealthTest(java.lang.Object, java.lang.Object)[pri:0, instance:io.mosip.actuator.healthcheck.test.ActuatorTest@21a06946] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setResultTestName -->
      </class> <!-- io.mosip.actuator.healthcheck.test.ActuatorTest -->
      <class name="io.mosip.preregistration.tests.PreRegistrationSmoke">
        <test-method status="FAIL" signature="generateOtp()[pri:1, instance:io.mosip.preregistration.tests.PreRegistrationSmoke@77f03bb1]" name="generateOtp" duration-ms="5429" started-at="2020-06-02T16:33:34Z" finished-at="2020-06-02T16:33:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at io.mosip.preregistration.tests.PreRegistrationSmoke.generateOtp(PreRegistrationSmoke.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:72)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.main(MosipTestRunner.java:35)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateOtp -->
        <test-method status="FAIL" signature="createApplication()[pri:2, instance:io.mosip.preregistration.tests.PreRegistrationSmoke@77f03bb1]" name="createApplication" duration-ms="363" started-at="2020-06-02T16:33:39Z" finished-at="2020-06-02T16:33:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at io.mosip.preregistration.tests.PreRegistrationSmoke.createApplication(PreRegistrationSmoke.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:72)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.main(MosipTestRunner.java:35)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createApplication -->
        <test-method status="FAIL" signature="documentUpload()[pri:3, instance:io.mosip.preregistration.tests.PreRegistrationSmoke@77f03bb1]" name="documentUpload" duration-ms="5" started-at="2020-06-02T16:33:40Z" finished-at="2020-06-02T16:33:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at io.mosip.preregistration.tests.PreRegistrationSmoke.documentUpload(PreRegistrationSmoke.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:72)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.main(MosipTestRunner.java:35)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- documentUpload -->
        <test-method status="FAIL" signature="fetchCenter()[pri:4, instance:io.mosip.preregistration.tests.PreRegistrationSmoke@77f03bb1]" name="fetchCenter" duration-ms="261" started-at="2020-06-02T16:33:40Z" finished-at="2020-06-02T16:33:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at io.mosip.preregistration.tests.PreRegistrationSmoke.fetchCenter(PreRegistrationSmoke.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:72)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.main(MosipTestRunner.java:35)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fetchCenter -->
        <test-method status="FAIL" signature="bookAppointment()[pri:5, instance:io.mosip.preregistration.tests.PreRegistrationSmoke@77f03bb1]" name="bookAppointment" duration-ms="6" started-at="2020-06-02T16:33:40Z" finished-at="2020-06-02T16:33:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at io.mosip.preregistration.tests.PreRegistrationSmoke.bookAppointment(PreRegistrationSmoke.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:72)
	at io.mosip.orchestrator.testrunner.MosipTestRunner.main(MosipTestRunner.java:35)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bookAppointment -->
        <test-method status="PASS" signature="insertIntoDb()[pri:0, instance:io.mosip.preregistration.tests.PreRegistrationSmoke@77f03bb1]" name="insertIntoDb" is-config="true" duration-ms="59" started-at="2020-06-02T16:33:40Z" finished-at="2020-06-02T16:33:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertIntoDb -->
      </class> <!-- io.mosip.preregistration.tests.PreRegistrationSmoke -->
    </test> <!-- HealthCheckTest -->
  </suite> <!-- HealthCheckSuite -->
</testng-results>
